task: fix undefined "port" variable rendering client task
With a recent change in ktoolbox.kjinja2.render_data(), the function
now errors out (by default) if an undefined variable is referenced.
That is useful, to find bugs about undefined variables in Jinja2
templates.

This now causes a crash:

   2025-03-19 18:01:40.629 INFO    [th:139630867451904]: Generate Client Pod Yaml "/mnt/runner/kubernetes-traffic-flow-tests/manifests/yamls/pod-ovn-worker2-client.yaml" (from "/mnt/runner/kubernetes-traffic-flow-tests/manifests/pod.yaml.j2", for IperfClient)
   Traceback (most recent call last):
     File "/mnt/runner/kubernetes-traffic-flow-tests/./tft.py", line 83, in <module>
       main()
     File "/mnt/runner/kubernetes-traffic-flow-tests/./tft.py", line 79, in main
       tft.test_run(cfg_descr, evaluator)
     File "/mnt/runner/kubernetes-traffic-flow-tests/trafficFlowTests.py", line 165, in test_run
       tft_results = self._run_test_cases(cfg_descr)
     File "/mnt/runner/kubernetes-traffic-flow-tests/trafficFlowTests.py", line 152, in _run_test_cases
       tft_results_lst.extend(self._run_test_case(cfg_descr2))
     File "/mnt/runner/kubernetes-traffic-flow-tests/trafficFlowTests.py", line 133, in _run_test_case
       self._run_test_case_instance(
     File "/mnt/runner/kubernetes-traffic-flow-tests/trafficFlowTests.py", line 97, in _run_test_case_instance
       t.initialize()
     File "/mnt/runner/kubernetes-traffic-flow-tests/task.py", line 943, in initialize
       self.render_file("Client Pod Yaml")
     File "/mnt/runner/kubernetes-traffic-flow-tests/task.py", line 368, in render_file
       rendered = kjinja2.render_file(
     File "/mnt/runner/kubernetes-traffic-flow-tests/tft-venv/lib/python3.10/site-packages/ktoolbox/kjinja2.py", line 48, in render_file
       return render_data(
     File "/mnt/runner/kubernetes-traffic-flow-tests/tft-venv/lib/python3.10/site-packages/ktoolbox/kjinja2.py", line 30, in render_data
       rendered = template.render(**a)
     File "/mnt/runner/kubernetes-traffic-flow-tests/tft-venv/lib/python3.10/site-packages/jinja2/environment.py", line 1295, in render
       self.environment.handle_exception()
     File "/mnt/runner/kubernetes-traffic-flow-tests/tft-venv/lib/python3.10/site-packages/jinja2/environment.py", line 942, in handle_exception
       raise rewrite_traceback_stack(source=source)
     File "<template>", line 8, in top-level template code
   jinja2.exceptions.UndefinedError: 'port' is undefined

Note how ClientTask.get_template_args() (and subclasses of ClientTask)
did not set the "port". This causes a crash tring to render
"pod.yaml.j2" (and other manifests).

So, while our manifest files also for the client pod refer to a
{{port}}, we must (explicitly) set it to empty. That is,
because the server pod uses `tft-port:{{port}}` as label for being
selected by the Service. The client must not have such a port.

This fixes the crash and restores the previous behavior.

Signed-off-by: Thomas Haller <thaller@redhat.com>